-- +goose Up
-- +goose StatementBegin

-- Every id in this schema is a ULID generated in Go: 26 characters of
-- Crockford base32, which sorts by creation time and so is its own pagination
-- cursor.
--
-- A domain rather than CHAR(26) on each column. CHAR pads a shorter value with
-- spaces, so a bad write becomes a value that silently no longer equals the
-- form it was written as -- and Postgres itself says CHAR has no advantage over
-- TEXT. This checks the alphabet too, which CHAR could not.
CREATE DOMAIN ulid AS TEXT
    CHECK (VALUE ~ '^[0-9A-HJKMNP-TV-Z]{26}$');

COMMENT ON DOMAIN ulid IS
    'Crockford base32, 26 chars. Generated by the application, never by the database.';

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP DOMAIN ulid;
-- +goose StatementEnd
