// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: notification/v1/common.proto

// Package notification.v1 is srosha's public contract. Everything a customer
// can say to this service, and everything it says back, is defined here and
// nowhere else.
//
// v1 is in the package name rather than only in the directory, because the
// package is what travels: two versions of a message with the same fully
// qualified name cannot coexist on one wire.

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Priority is how far ahead of other traffic a message goes.
//
// UNSPECIFIED is the zero value and means "the source did not say", which the
// service reads as NORMAL. proto3 cannot tell an unset field from one set to
// its zero value, so a meaningful zero would make "I did not choose" and "I
// chose the lowest" the same request.
//
// Each source has a ceiling. Asking above it is not an error: the request is
// accepted at the ceiling and the answer says the priority was lowered, so a
// customer learns about their limit rather than losing the message to it.
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_NORMAL      Priority = 1
	Priority_PRIORITY_HIGH        Priority = 2
	Priority_PRIORITY_CRITICAL    Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_NORMAL",
		2: "PRIORITY_HIGH",
		3: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_NORMAL":      1,
		"PRIORITY_HIGH":        2,
		"PRIORITY_CRITICAL":    3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_common_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_notification_v1_common_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_common_proto_rawDescGZIP(), []int{0}
}

// Channel is how a message travels.
type Channel int32

const (
	Channel_CHANNEL_UNSPECIFIED Channel = 0
	Channel_CHANNEL_EMAIL       Channel = 1
	Channel_CHANNEL_TELEGRAM    Channel = 2
	Channel_CHANNEL_BALE        Channel = 3
	Channel_CHANNEL_WHATSAPP    Channel = 4
	Channel_CHANNEL_MATRIX      Channel = 5
	Channel_CHANNEL_FCM         Channel = 6
	Channel_CHANNEL_APNS        Channel = 7
	Channel_CHANNEL_GOTIFY      Channel = 8
)

// Enum value maps for Channel.
var (
	Channel_name = map[int32]string{
		0: "CHANNEL_UNSPECIFIED",
		1: "CHANNEL_EMAIL",
		2: "CHANNEL_TELEGRAM",
		3: "CHANNEL_BALE",
		4: "CHANNEL_WHATSAPP",
		5: "CHANNEL_MATRIX",
		6: "CHANNEL_FCM",
		7: "CHANNEL_APNS",
		8: "CHANNEL_GOTIFY",
	}
	Channel_value = map[string]int32{
		"CHANNEL_UNSPECIFIED": 0,
		"CHANNEL_EMAIL":       1,
		"CHANNEL_TELEGRAM":    2,
		"CHANNEL_BALE":        3,
		"CHANNEL_WHATSAPP":    4,
		"CHANNEL_MATRIX":      5,
		"CHANNEL_FCM":         6,
		"CHANNEL_APNS":        7,
		"CHANNEL_GOTIFY":      8,
	}
)

func (x Channel) Enum() *Channel {
	p := new(Channel)
	*p = x
	return p
}

func (x Channel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Channel) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_common_proto_enumTypes[1].Descriptor()
}

func (Channel) Type() protoreflect.EnumType {
	return &file_notification_v1_common_proto_enumTypes[1]
}

func (x Channel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Channel.Descriptor instead.
func (Channel) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_common_proto_rawDescGZIP(), []int{1}
}

// Window is how far back a listing reaches.
//
// A closed set rather than two timestamps the caller picks, because this
// service is not an archive: past the retention age a message is deleted, and
// a range reaching beyond it comes back short with nothing saying so. An empty
// answer would then mean two things at once -- "you sent nothing" and "you sent
// something we no longer have" -- and the caller cannot tell which.
//
// UNSPECIFIED is not "no window". It means as far back as this deployment
// keeps, and it is the only value that is right whatever that age is set to,
// because it names no number of its own. Any other value longer than the
// retention age is refused, and the answer says how far back it can go.
type Window int32

const (
	Window_WINDOW_UNSPECIFIED Window = 0
	Window_WINDOW_LAST_HOUR   Window = 1
	Window_WINDOW_LAST_DAY    Window = 2
	Window_WINDOW_LAST_WEEK   Window = 3
	Window_WINDOW_LAST_MONTH  Window = 4
)

// Enum value maps for Window.
var (
	Window_name = map[int32]string{
		0: "WINDOW_UNSPECIFIED",
		1: "WINDOW_LAST_HOUR",
		2: "WINDOW_LAST_DAY",
		3: "WINDOW_LAST_WEEK",
		4: "WINDOW_LAST_MONTH",
	}
	Window_value = map[string]int32{
		"WINDOW_UNSPECIFIED": 0,
		"WINDOW_LAST_HOUR":   1,
		"WINDOW_LAST_DAY":    2,
		"WINDOW_LAST_WEEK":   3,
		"WINDOW_LAST_MONTH":  4,
	}
)

func (x Window) Enum() *Window {
	p := new(Window)
	*p = x
	return p
}

func (x Window) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Window) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_common_proto_enumTypes[2].Descriptor()
}

func (Window) Type() protoreflect.EnumType {
	return &file_notification_v1_common_proto_enumTypes[2]
}

func (x Window) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Window.Descriptor instead.
func (Window) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_common_proto_rawDescGZIP(), []int{2}
}

// DeliveryStatus is what happened to one recipient.
//
// There is no RETRYING. A delivery that failed transiently stays PENDING and is
// tried again; only an outcome that will not change is written down. A status
// that changed back and forth would tell a customer nothing they could act on.
type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_PENDING     DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_SENT        DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 3
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_PENDING",
		2: "DELIVERY_STATUS_SENT",
		3: "DELIVERY_STATUS_FAILED",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_PENDING":     1,
		"DELIVERY_STATUS_SENT":        2,
		"DELIVERY_STATUS_FAILED":      3,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_common_proto_enumTypes[3].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_notification_v1_common_proto_enumTypes[3]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_common_proto_rawDescGZIP(), []int{3}
}

// FailureReason says why a delivery will not be retried.
//
// It is a fixed set rather than the provider's own error text. That text is
// written for operators and can name hosts, limits and internals; this says
// what happened with none of it.
type FailureReason int32

const (
	FailureReason_FAILURE_REASON_UNSPECIFIED FailureReason = 0
	// The message outlived its expiry before its turn came.
	FailureReason_FAILURE_REASON_EXPIRED FailureReason = 1
	// Attempts ran out while the failures were still the kind that might have
	// passed later.
	FailureReason_FAILURE_REASON_MAX_ATTEMPTS FailureReason = 2
	// The provider refused in a way that repeating will not fix: a bad address,
	// a blocked recipient, a message it will never accept.
	FailureReason_FAILURE_REASON_PERMANENT FailureReason = 3
	// The source has no sending identity configured for that channel. A
	// configuration answer, not a provider one -- it will read the same on every
	// retry until somebody changes the setup.
	FailureReason_FAILURE_REASON_NO_SENDER FailureReason = 4
	// The provider refused the RECIPIENT rather than the message: somebody who
	// blocked us, a conversation window that closed, a device token no longer
	// registered.
	//
	// Apart from PERMANENT because you can act on it and cannot act on that one:
	// nothing written differently would have helped. Somebody has to open a
	// conversation, or a token has to be replaced.
	FailureReason_FAILURE_REASON_NOT_REACHABLE FailureReason = 5
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0: "FAILURE_REASON_UNSPECIFIED",
		1: "FAILURE_REASON_EXPIRED",
		2: "FAILURE_REASON_MAX_ATTEMPTS",
		3: "FAILURE_REASON_PERMANENT",
		4: "FAILURE_REASON_NO_SENDER",
		5: "FAILURE_REASON_NOT_REACHABLE",
	}
	FailureReason_value = map[string]int32{
		"FAILURE_REASON_UNSPECIFIED":   0,
		"FAILURE_REASON_EXPIRED":       1,
		"FAILURE_REASON_MAX_ATTEMPTS":  2,
		"FAILURE_REASON_PERMANENT":     3,
		"FAILURE_REASON_NO_SENDER":     4,
		"FAILURE_REASON_NOT_REACHABLE": 5,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_common_proto_enumTypes[4].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_notification_v1_common_proto_enumTypes[4]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_common_proto_rawDescGZIP(), []int{4}
}

// Page is where a listing carries on from.
//
// after is an id, not an offset. An offset makes the database count and throw
// away every row before the page, and it skips or repeats rows when the set
// changes underneath; an id does neither.
type Page struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty for the first page. Otherwise the next_page_token of the last answer.
	After string `protobuf:"bytes,1,opt,name=after,proto3" json:"after,omitempty"`
	// Zero means the service's default. Above its ceiling is clamped rather than
	// refused -- asking for too much is not a mistake worth failing a request for.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_notification_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_notification_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *Page) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_notification_v1_common_proto protoreflect.FileDescriptor

const file_notification_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1cnotification/v1/common.proto\x12\x0fnotification.v1\"2\n" +
	"\x04Page\x12\x14\n" +
	"\x05after\x18\x01 \x01(\tR\x05after\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit*c\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x01\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x02\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10\x03*\xbe\x01\n" +
	"\aChannel\x12\x17\n" +
	"\x13CHANNEL_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rCHANNEL_EMAIL\x10\x01\x12\x14\n" +
	"\x10CHANNEL_TELEGRAM\x10\x02\x12\x10\n" +
	"\fCHANNEL_BALE\x10\x03\x12\x14\n" +
	"\x10CHANNEL_WHATSAPP\x10\x04\x12\x12\n" +
	"\x0eCHANNEL_MATRIX\x10\x05\x12\x0f\n" +
	"\vCHANNEL_FCM\x10\x06\x12\x10\n" +
	"\fCHANNEL_APNS\x10\a\x12\x12\n" +
	"\x0eCHANNEL_GOTIFY\x10\b*x\n" +
	"\x06Window\x12\x16\n" +
	"\x12WINDOW_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10WINDOW_LAST_HOUR\x10\x01\x12\x13\n" +
	"\x0fWINDOW_LAST_DAY\x10\x02\x12\x14\n" +
	"\x10WINDOW_LAST_WEEK\x10\x03\x12\x15\n" +
	"\x11WINDOW_LAST_MONTH\x10\x04*\x84\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14DELIVERY_STATUS_SENT\x10\x02\x12\x1a\n" +
	"\x16DELIVERY_STATUS_FAILED\x10\x03*\xca\x01\n" +
	"\rFailureReason\x12\x1e\n" +
	"\x1aFAILURE_REASON_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FAILURE_REASON_EXPIRED\x10\x01\x12\x1f\n" +
	"\x1bFAILURE_REASON_MAX_ATTEMPTS\x10\x02\x12\x1c\n" +
	"\x18FAILURE_REASON_PERMANENT\x10\x03\x12\x1c\n" +
	"\x18FAILURE_REASON_NO_SENDER\x10\x04\x12 \n" +
	"\x1cFAILURE_REASON_NOT_REACHABLE\x10\x05B\xc1\x01\n" +
	"\x13com.notification.v1B\vCommonProtoP\x01Z@github.com/Serajian/srosha/sdk/go/notification/v1;notificationv1\xa2\x02\x03NXX\xaa\x02\x0fNotification.V1\xca\x02\x0fNotification\\V1\xe2\x02\x1bNotification\\V1\\GPBMetadata\xea\x02\x10Notification::V1b\x06proto3"

var (
	file_notification_v1_common_proto_rawDescOnce sync.Once
	file_notification_v1_common_proto_rawDescData []byte
)

func file_notification_v1_common_proto_rawDescGZIP() []byte {
	file_notification_v1_common_proto_rawDescOnce.Do(func() {
		file_notification_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_common_proto_rawDesc), len(file_notification_v1_common_proto_rawDesc)))
	})
	return file_notification_v1_common_proto_rawDescData
}

var file_notification_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_notification_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notification_v1_common_proto_goTypes = []any{
	(Priority)(0),       // 0: notification.v1.Priority
	(Channel)(0),        // 1: notification.v1.Channel
	(Window)(0),         // 2: notification.v1.Window
	(DeliveryStatus)(0), // 3: notification.v1.DeliveryStatus
	(FailureReason)(0),  // 4: notification.v1.FailureReason
	(*Page)(nil),        // 5: notification.v1.Page
}
var file_notification_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_v1_common_proto_init() }
func file_notification_v1_common_proto_init() {
	if File_notification_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_common_proto_rawDesc), len(file_notification_v1_common_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_v1_common_proto_goTypes,
		DependencyIndexes: file_notification_v1_common_proto_depIdxs,
		EnumInfos:         file_notification_v1_common_proto_enumTypes,
		MessageInfos:      file_notification_v1_common_proto_msgTypes,
	}.Build()
	File_notification_v1_common_proto = out.File
	file_notification_v1_common_proto_goTypes = nil
	file_notification_v1_common_proto_depIdxs = nil
}
