// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: notification/v1/credential.proto

package notificationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialService_Register_FullMethodName   = "/notification.v1.CredentialService/Register"
	CredentialService_List_FullMethodName       = "/notification.v1.CredentialService/List"
	CredentialService_Deactivate_FullMethodName = "/notification.v1.CredentialService/Deactivate"
	CredentialService_Activate_FullMethodName   = "/notification.v1.CredentialService/Activate"
	CredentialService_SetDefault_FullMethodName = "/notification.v1.CredentialService/SetDefault"
	CredentialService_Rotate_FullMethodName     = "/notification.v1.CredentialService/Rotate"
	CredentialService_Update_FullMethodName     = "/notification.v1.CredentialService/Update"
)

// CredentialServiceClient is the client API for CredentialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CredentialService manages the sending identities a source sends as: which
// Telegram bot, which SMTP account.
//
// A source that registers none still sends -- srosha's own credentials are used
// then. This is for a customer who wants their messages to arrive from their own
// bot rather than ours.
//
// As in the other services, no request carries a source id. Which source is
// calling comes from their key.
type CredentialServiceClient interface {
	// Register opens an identity on one channel. The name is how a message asks
	// for it later, in SubmitRequest's Route.sender.
	Register(ctx context.Context, in *CredentialServiceRegisterRequest, opts ...grpc.CallOption) (*CredentialServiceRegisterResponse, error)
	// List answers "what have I registered". Switched-off identities are in it,
	// and that is the point: without them nobody can turn one back on.
	List(ctx context.Context, in *CredentialServiceListRequest, opts ...grpc.CallOption) (*CredentialServiceListResponse, error)
	// Deactivate stops an identity being used without forgetting it, so turning
	// it back on is not a re-registration. Nothing here deletes: after an incident
	// the first question is when an identity was withdrawn, and a deleted row
	// answers nothing.
	//
	// If it held the default, the channel is left with none until SetDefault names
	// one. Guessing which should take over would move it silently.
	Deactivate(ctx context.Context, in *CredentialServiceDeactivateRequest, opts ...grpc.CallOption) (*CredentialServiceDeactivateResponse, error)
	// Activate is the way back. It does not hand the default back.
	Activate(ctx context.Context, in *CredentialServiceActivateRequest, opts ...grpc.CallOption) (*CredentialServiceActivateResponse, error)
	// SetDefault moves which identity a message that names none uses. A channel
	// has at most one, so this takes it from whichever held it.
	SetDefault(ctx context.Context, in *CredentialServiceSetDefaultRequest, opts ...grpc.CallOption) (*CredentialServiceSetDefaultResponse, error)
	// Rotate replaces the secret and keeps the name, which is what a leaked token
	// needs: registering a second identity instead would make every message still
	// naming the old one fail, turning a leak into a code change.
	Rotate(ctx context.Context, in *CredentialServiceRotateRequest, opts ...grpc.CallOption) (*CredentialServiceRotateResponse, error)
	// Update replaces the provider settings and keeps the name, because a message
	// asks for an identity by name: renaming would break every message still
	// naming it. Changing a mail server is what this is for -- registering a
	// second identity instead would do exactly that damage.
	Update(ctx context.Context, in *CredentialServiceUpdateRequest, opts ...grpc.CallOption) (*CredentialServiceUpdateResponse, error)
}

type credentialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialServiceClient(cc grpc.ClientConnInterface) CredentialServiceClient {
	return &credentialServiceClient{cc}
}

func (c *credentialServiceClient) Register(ctx context.Context, in *CredentialServiceRegisterRequest, opts ...grpc.CallOption) (*CredentialServiceRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialServiceRegisterResponse)
	err := c.cc.Invoke(ctx, CredentialService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) List(ctx context.Context, in *CredentialServiceListRequest, opts ...grpc.CallOption) (*CredentialServiceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialServiceListResponse)
	err := c.cc.Invoke(ctx, CredentialService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) Deactivate(ctx context.Context, in *CredentialServiceDeactivateRequest, opts ...grpc.CallOption) (*CredentialServiceDeactivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialServiceDeactivateResponse)
	err := c.cc.Invoke(ctx, CredentialService_Deactivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) Activate(ctx context.Context, in *CredentialServiceActivateRequest, opts ...grpc.CallOption) (*CredentialServiceActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialServiceActivateResponse)
	err := c.cc.Invoke(ctx, CredentialService_Activate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) SetDefault(ctx context.Context, in *CredentialServiceSetDefaultRequest, opts ...grpc.CallOption) (*CredentialServiceSetDefaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialServiceSetDefaultResponse)
	err := c.cc.Invoke(ctx, CredentialService_SetDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) Rotate(ctx context.Context, in *CredentialServiceRotateRequest, opts ...grpc.CallOption) (*CredentialServiceRotateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialServiceRotateResponse)
	err := c.cc.Invoke(ctx, CredentialService_Rotate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialServiceClient) Update(ctx context.Context, in *CredentialServiceUpdateRequest, opts ...grpc.CallOption) (*CredentialServiceUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CredentialServiceUpdateResponse)
	err := c.cc.Invoke(ctx, CredentialService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialServiceServer is the server API for CredentialService service.
// All implementations must embed UnimplementedCredentialServiceServer
// for forward compatibility.
//
// CredentialService manages the sending identities a source sends as: which
// Telegram bot, which SMTP account.
//
// A source that registers none still sends -- srosha's own credentials are used
// then. This is for a customer who wants their messages to arrive from their own
// bot rather than ours.
//
// As in the other services, no request carries a source id. Which source is
// calling comes from their key.
type CredentialServiceServer interface {
	// Register opens an identity on one channel. The name is how a message asks
	// for it later, in SubmitRequest's Route.sender.
	Register(context.Context, *CredentialServiceRegisterRequest) (*CredentialServiceRegisterResponse, error)
	// List answers "what have I registered". Switched-off identities are in it,
	// and that is the point: without them nobody can turn one back on.
	List(context.Context, *CredentialServiceListRequest) (*CredentialServiceListResponse, error)
	// Deactivate stops an identity being used without forgetting it, so turning
	// it back on is not a re-registration. Nothing here deletes: after an incident
	// the first question is when an identity was withdrawn, and a deleted row
	// answers nothing.
	//
	// If it held the default, the channel is left with none until SetDefault names
	// one. Guessing which should take over would move it silently.
	Deactivate(context.Context, *CredentialServiceDeactivateRequest) (*CredentialServiceDeactivateResponse, error)
	// Activate is the way back. It does not hand the default back.
	Activate(context.Context, *CredentialServiceActivateRequest) (*CredentialServiceActivateResponse, error)
	// SetDefault moves which identity a message that names none uses. A channel
	// has at most one, so this takes it from whichever held it.
	SetDefault(context.Context, *CredentialServiceSetDefaultRequest) (*CredentialServiceSetDefaultResponse, error)
	// Rotate replaces the secret and keeps the name, which is what a leaked token
	// needs: registering a second identity instead would make every message still
	// naming the old one fail, turning a leak into a code change.
	Rotate(context.Context, *CredentialServiceRotateRequest) (*CredentialServiceRotateResponse, error)
	// Update replaces the provider settings and keeps the name, because a message
	// asks for an identity by name: renaming would break every message still
	// naming it. Changing a mail server is what this is for -- registering a
	// second identity instead would do exactly that damage.
	Update(context.Context, *CredentialServiceUpdateRequest) (*CredentialServiceUpdateResponse, error)
	mustEmbedUnimplementedCredentialServiceServer()
}

// UnimplementedCredentialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialServiceServer struct{}

func (UnimplementedCredentialServiceServer) Register(context.Context, *CredentialServiceRegisterRequest) (*CredentialServiceRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCredentialServiceServer) List(context.Context, *CredentialServiceListRequest) (*CredentialServiceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCredentialServiceServer) Deactivate(context.Context, *CredentialServiceDeactivateRequest) (*CredentialServiceDeactivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deactivate not implemented")
}
func (UnimplementedCredentialServiceServer) Activate(context.Context, *CredentialServiceActivateRequest) (*CredentialServiceActivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Activate not implemented")
}
func (UnimplementedCredentialServiceServer) SetDefault(context.Context, *CredentialServiceSetDefaultRequest) (*CredentialServiceSetDefaultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefault not implemented")
}
func (UnimplementedCredentialServiceServer) Rotate(context.Context, *CredentialServiceRotateRequest) (*CredentialServiceRotateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rotate not implemented")
}
func (UnimplementedCredentialServiceServer) Update(context.Context, *CredentialServiceUpdateRequest) (*CredentialServiceUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCredentialServiceServer) mustEmbedUnimplementedCredentialServiceServer() {}
func (UnimplementedCredentialServiceServer) testEmbeddedByValue()                           {}

// UnsafeCredentialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialServiceServer will
// result in compilation errors.
type UnsafeCredentialServiceServer interface {
	mustEmbedUnimplementedCredentialServiceServer()
}

func RegisterCredentialServiceServer(s grpc.ServiceRegistrar, srv CredentialServiceServer) {
	// If the following call panics, it indicates UnimplementedCredentialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialService_ServiceDesc, srv)
}

func _CredentialService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialServiceRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Register(ctx, req.(*CredentialServiceRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).List(ctx, req.(*CredentialServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_Deactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialServiceDeactivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Deactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_Deactivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Deactivate(ctx, req.(*CredentialServiceDeactivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialServiceActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_Activate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Activate(ctx, req.(*CredentialServiceActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_SetDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialServiceSetDefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).SetDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_SetDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).SetDefault(ctx, req.(*CredentialServiceSetDefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_Rotate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialServiceRotateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Rotate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_Rotate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Rotate(ctx, req.(*CredentialServiceRotateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CredentialService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialServiceUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CredentialService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialServiceServer).Update(ctx, req.(*CredentialServiceUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CredentialService_ServiceDesc is the grpc.ServiceDesc for CredentialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.v1.CredentialService",
	HandlerType: (*CredentialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _CredentialService_Register_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CredentialService_List_Handler,
		},
		{
			MethodName: "Deactivate",
			Handler:    _CredentialService_Deactivate_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _CredentialService_Activate_Handler,
		},
		{
			MethodName: "SetDefault",
			Handler:    _CredentialService_SetDefault_Handler,
		},
		{
			MethodName: "Rotate",
			Handler:    _CredentialService_Rotate_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CredentialService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/v1/credential.proto",
}
