// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: notification/v1/source.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhoamiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiRequest) Reset() {
	*x = WhoamiRequest{}
	mi := &file_notification_v1_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiRequest) ProtoMessage() {}

func (x *WhoamiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiRequest.ProtoReflect.Descriptor instead.
func (*WhoamiRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_source_proto_rawDescGZIP(), []int{0}
}

type WhoamiResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The caller's own id, which is what support asks for.
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The highest priority this source may send at. Asking above it is not an
	// error: the message is accepted here and the answer says it was lowered.
	MaxPriority Priority `protobuf:"varint,3,opt,name=max_priority,json=maxPriority,proto3,enum=notification.v1.Priority" json:"max_priority,omitempty"`
	// Whether a message may name its own recipient. When false, the only
	// addresses this source can reach are the ones below -- which is what bounds
	// where a leaked key can send.
	AllowCustomAddress bool `protobuf:"varint,4,opt,name=allow_custom_address,json=allowCustomAddress,proto3" json:"allow_custom_address,omitempty"`
	// The address used on a channel when a route names none, keyed by channel
	// name. Empty for a channel with no default.
	//
	// Keyed by name rather than by the Channel enum because proto3 map keys
	// cannot be enums, and a name survives this service learning a channel the
	// caller's build has never heard of.
	DefaultAddresses map[string]string `protobuf:"bytes,5,rep,name=default_addresses,json=defaultAddresses,proto3" json:"default_addresses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// How long a message and its deliveries are kept. Past this they are deleted,
	// which is why a listing window may not reach further back.
	//
	// A duration rather than the largest Window that fits, because it is the
	// honest number: a deployment keeping ten days has no Window that says so,
	// and rounding it down here would hide the four days a client could still
	// have asked about.
	Retention *durationpb.Duration `protobuf:"bytes,6,opt,name=retention,proto3" json:"retention,omitempty"`
	// Requests per minute, counted per source. Going over is ResourceExhausted
	// and clears with time.
	RateLimitPerMinute int32 `protobuf:"varint,7,opt,name=rate_limit_per_minute,json=rateLimitPerMinute,proto3" json:"rate_limit_per_minute,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WhoamiResponse) Reset() {
	*x = WhoamiResponse{}
	mi := &file_notification_v1_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiResponse) ProtoMessage() {}

func (x *WhoamiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiResponse.ProtoReflect.Descriptor instead.
func (*WhoamiResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_source_proto_rawDescGZIP(), []int{1}
}

func (x *WhoamiResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WhoamiResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WhoamiResponse) GetMaxPriority() Priority {
	if x != nil {
		return x.MaxPriority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *WhoamiResponse) GetAllowCustomAddress() bool {
	if x != nil {
		return x.AllowCustomAddress
	}
	return false
}

func (x *WhoamiResponse) GetDefaultAddresses() map[string]string {
	if x != nil {
		return x.DefaultAddresses
	}
	return nil
}

func (x *WhoamiResponse) GetRetention() *durationpb.Duration {
	if x != nil {
		return x.Retention
	}
	return nil
}

func (x *WhoamiResponse) GetRateLimitPerMinute() int32 {
	if x != nil {
		return x.RateLimitPerMinute
	}
	return 0
}

var File_notification_v1_source_proto protoreflect.FileDescriptor

const file_notification_v1_source_proto_rawDesc = "" +
	"\n" +
	"\x1cnotification/v1/source.proto\x12\x0fnotification.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cnotification/v1/common.proto\"\x0f\n" +
	"\rWhoamiRequest\"\xb9\x03\n" +
	"\x0eWhoamiResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12<\n" +
	"\fmax_priority\x18\x03 \x01(\x0e2\x19.notification.v1.PriorityR\vmaxPriority\x120\n" +
	"\x14allow_custom_address\x18\x04 \x01(\bR\x12allowCustomAddress\x12b\n" +
	"\x11default_addresses\x18\x05 \x03(\v25.notification.v1.WhoamiResponse.DefaultAddressesEntryR\x10defaultAddresses\x127\n" +
	"\tretention\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\tretention\x121\n" +
	"\x15rate_limit_per_minute\x18\a \x01(\x05R\x12rateLimitPerMinute\x1aC\n" +
	"\x15DefaultAddressesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012Z\n" +
	"\rSourceService\x12I\n" +
	"\x06Whoami\x12\x1e.notification.v1.WhoamiRequest\x1a\x1f.notification.v1.WhoamiResponseB\xc1\x01\n" +
	"\x13com.notification.v1B\vSourceProtoP\x01Z@github.com/Serajian/srosha/sdk/go/notification/v1;notificationv1\xa2\x02\x03NXX\xaa\x02\x0fNotification.V1\xca\x02\x0fNotification\\V1\xe2\x02\x1bNotification\\V1\\GPBMetadata\xea\x02\x10Notification::V1b\x06proto3"

var (
	file_notification_v1_source_proto_rawDescOnce sync.Once
	file_notification_v1_source_proto_rawDescData []byte
)

func file_notification_v1_source_proto_rawDescGZIP() []byte {
	file_notification_v1_source_proto_rawDescOnce.Do(func() {
		file_notification_v1_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_source_proto_rawDesc), len(file_notification_v1_source_proto_rawDesc)))
	})
	return file_notification_v1_source_proto_rawDescData
}

var file_notification_v1_source_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_notification_v1_source_proto_goTypes = []any{
	(*WhoamiRequest)(nil),       // 0: notification.v1.WhoamiRequest
	(*WhoamiResponse)(nil),      // 1: notification.v1.WhoamiResponse
	nil,                         // 2: notification.v1.WhoamiResponse.DefaultAddressesEntry
	(Priority)(0),               // 3: notification.v1.Priority
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
}
var file_notification_v1_source_proto_depIdxs = []int32{
	3, // 0: notification.v1.WhoamiResponse.max_priority:type_name -> notification.v1.Priority
	2, // 1: notification.v1.WhoamiResponse.default_addresses:type_name -> notification.v1.WhoamiResponse.DefaultAddressesEntry
	4, // 2: notification.v1.WhoamiResponse.retention:type_name -> google.protobuf.Duration
	0, // 3: notification.v1.SourceService.Whoami:input_type -> notification.v1.WhoamiRequest
	1, // 4: notification.v1.SourceService.Whoami:output_type -> notification.v1.WhoamiResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_notification_v1_source_proto_init() }
func file_notification_v1_source_proto_init() {
	if File_notification_v1_source_proto != nil {
		return
	}
	file_notification_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_source_proto_rawDesc), len(file_notification_v1_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_source_proto_goTypes,
		DependencyIndexes: file_notification_v1_source_proto_depIdxs,
		MessageInfos:      file_notification_v1_source_proto_msgTypes,
	}.Build()
	File_notification_v1_source_proto = out.File
	file_notification_v1_source_proto_goTypes = nil
	file_notification_v1_source_proto_depIdxs = nil
}
