// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: notification/v1/source.proto

package notificationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SourceService_Whoami_FullMethodName = "/notification.v1.SourceService/Whoami"
)

// SourceServiceClient is the client API for SourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SourceService answers questions a caller has about itself.
//
// A service of its own because it manages nothing: the others are named for the
// noun they own -- notifications, credentials, webhooks -- and this one is
// about whoever is asking. Filing it under any of them would put it somewhere
// nobody would look.
type SourceServiceClient interface {
	// Whoami says who the caller is and what they are allowed.
	//
	// It exists because nothing else answers those questions until you get them
	// wrong. A ceiling shows up as a priority that was lowered; a retention
	// window shows up as a listing that was refused. Both are knowable in
	// advance, and this is where.
	//
	// It also proves, in one call, that the address is right and the key works.
	// A client connects lazily, so without this the first news of a wrong address
	// or a bad key arrives on the first message that mattered.
	//
	// Not a health check. It authenticates and counts against the caller's rate
	// limit like everything else, and a successful answer says nothing about the
	// next call -- keys are revoked and networks part between them. Call it when
	// a process starts, not on a timer.
	Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*WhoamiResponse, error)
}

type sourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceServiceClient(cc grpc.ClientConnInterface) SourceServiceClient {
	return &sourceServiceClient{cc}
}

func (c *sourceServiceClient) Whoami(ctx context.Context, in *WhoamiRequest, opts ...grpc.CallOption) (*WhoamiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoamiResponse)
	err := c.cc.Invoke(ctx, SourceService_Whoami_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceServiceServer is the server API for SourceService service.
// All implementations must embed UnimplementedSourceServiceServer
// for forward compatibility.
//
// SourceService answers questions a caller has about itself.
//
// A service of its own because it manages nothing: the others are named for the
// noun they own -- notifications, credentials, webhooks -- and this one is
// about whoever is asking. Filing it under any of them would put it somewhere
// nobody would look.
type SourceServiceServer interface {
	// Whoami says who the caller is and what they are allowed.
	//
	// It exists because nothing else answers those questions until you get them
	// wrong. A ceiling shows up as a priority that was lowered; a retention
	// window shows up as a listing that was refused. Both are knowable in
	// advance, and this is where.
	//
	// It also proves, in one call, that the address is right and the key works.
	// A client connects lazily, so without this the first news of a wrong address
	// or a bad key arrives on the first message that mattered.
	//
	// Not a health check. It authenticates and counts against the caller's rate
	// limit like everything else, and a successful answer says nothing about the
	// next call -- keys are revoked and networks part between them. Call it when
	// a process starts, not on a timer.
	Whoami(context.Context, *WhoamiRequest) (*WhoamiResponse, error)
	mustEmbedUnimplementedSourceServiceServer()
}

// UnimplementedSourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceServiceServer struct{}

func (UnimplementedSourceServiceServer) Whoami(context.Context, *WhoamiRequest) (*WhoamiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Whoami not implemented")
}
func (UnimplementedSourceServiceServer) mustEmbedUnimplementedSourceServiceServer() {}
func (UnimplementedSourceServiceServer) testEmbeddedByValue()                       {}

// UnsafeSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceServiceServer will
// result in compilation errors.
type UnsafeSourceServiceServer interface {
	mustEmbedUnimplementedSourceServiceServer()
}

func RegisterSourceServiceServer(s grpc.ServiceRegistrar, srv SourceServiceServer) {
	// If the following call panics, it indicates UnimplementedSourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourceService_ServiceDesc, srv)
}

func _SourceService_Whoami_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoamiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceServiceServer).Whoami(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceService_Whoami_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceServiceServer).Whoami(ctx, req.(*WhoamiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceService_ServiceDesc is the grpc.ServiceDesc for SourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.v1.SourceService",
	HandlerType: (*SourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Whoami",
			Handler:    _SourceService_Whoami_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/v1/source.proto",
}
