// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: notification/v1/webhook.proto

package notificationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookService_Register_FullMethodName     = "/notification.v1.WebhookService/Register"
	WebhookService_Get_FullMethodName          = "/notification.v1.WebhookService/Get"
	WebhookService_Deactivate_FullMethodName   = "/notification.v1.WebhookService/Deactivate"
	WebhookService_Activate_FullMethodName     = "/notification.v1.WebhookService/Activate"
	WebhookService_RotateSecret_FullMethodName = "/notification.v1.WebhookService/RotateSecret"
)

// WebhookServiceClient is the client API for WebhookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebhookService manages where a source wants delivery outcomes pushed to.
//
// The callback is a convenience on top of NotificationService.Get, not a
// replacement for it: it is sent once and never retried, so a source that must
// not miss an outcome asks for it.
//
// As in NotificationService, no request carries a source id. One source has one
// callback, and which source is the caller comes from their key.
type WebhookServiceClient interface {
	// Register sets the callback. Registering again moves the existing one rather
	// than adding a second, and gives the new address a clean start -- switched
	// on, failure count cleared. If we had switched the old one off for being
	// dead, that says nothing about the new one.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Get(ctx context.Context, in *WebhookServiceGetRequest, opts ...grpc.CallOption) (*WebhookServiceGetResponse, error)
	// Deactivate stops the callbacks without forgetting the address, so turning
	// them back on is not a re-registration.
	Deactivate(ctx context.Context, in *DeactivateRequest, opts ...grpc.CallOption) (*DeactivateResponse, error)
	// Activate is the way back, and clears the failure count: a callback that was
	// switched off for being dead must not be switched off again by the first
	// hiccup after it was fixed.
	Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error)
	// RotateSecret issues a new signing secret and returns it once.
	//
	// It exists because the secret is shown once and kept sealed: without it, a
	// source that lost theirs could never verify another callback again. Every
	// receiver still checking with the old one starts failing the moment this
	// returns, which is what a rotation is.
	RotateSecret(ctx context.Context, in *RotateSecretRequest, opts ...grpc.CallOption) (*RotateSecretResponse, error)
}

type webhookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookServiceClient(cc grpc.ClientConnInterface) WebhookServiceClient {
	return &webhookServiceClient{cc}
}

func (c *webhookServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, WebhookService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) Get(ctx context.Context, in *WebhookServiceGetRequest, opts ...grpc.CallOption) (*WebhookServiceGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookServiceGetResponse)
	err := c.cc.Invoke(ctx, WebhookService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) Deactivate(ctx context.Context, in *DeactivateRequest, opts ...grpc.CallOption) (*DeactivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateResponse)
	err := c.cc.Invoke(ctx, WebhookService_Deactivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) Activate(ctx context.Context, in *ActivateRequest, opts ...grpc.CallOption) (*ActivateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateResponse)
	err := c.cc.Invoke(ctx, WebhookService_Activate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) RotateSecret(ctx context.Context, in *RotateSecretRequest, opts ...grpc.CallOption) (*RotateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateSecretResponse)
	err := c.cc.Invoke(ctx, WebhookService_RotateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookServiceServer is the server API for WebhookService service.
// All implementations must embed UnimplementedWebhookServiceServer
// for forward compatibility.
//
// WebhookService manages where a source wants delivery outcomes pushed to.
//
// The callback is a convenience on top of NotificationService.Get, not a
// replacement for it: it is sent once and never retried, so a source that must
// not miss an outcome asks for it.
//
// As in NotificationService, no request carries a source id. One source has one
// callback, and which source is the caller comes from their key.
type WebhookServiceServer interface {
	// Register sets the callback. Registering again moves the existing one rather
	// than adding a second, and gives the new address a clean start -- switched
	// on, failure count cleared. If we had switched the old one off for being
	// dead, that says nothing about the new one.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Get(context.Context, *WebhookServiceGetRequest) (*WebhookServiceGetResponse, error)
	// Deactivate stops the callbacks without forgetting the address, so turning
	// them back on is not a re-registration.
	Deactivate(context.Context, *DeactivateRequest) (*DeactivateResponse, error)
	// Activate is the way back, and clears the failure count: a callback that was
	// switched off for being dead must not be switched off again by the first
	// hiccup after it was fixed.
	Activate(context.Context, *ActivateRequest) (*ActivateResponse, error)
	// RotateSecret issues a new signing secret and returns it once.
	//
	// It exists because the secret is shown once and kept sealed: without it, a
	// source that lost theirs could never verify another callback again. Every
	// receiver still checking with the old one starts failing the moment this
	// returns, which is what a rotation is.
	RotateSecret(context.Context, *RotateSecretRequest) (*RotateSecretResponse, error)
	mustEmbedUnimplementedWebhookServiceServer()
}

// UnimplementedWebhookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookServiceServer struct{}

func (UnimplementedWebhookServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedWebhookServiceServer) Get(context.Context, *WebhookServiceGetRequest) (*WebhookServiceGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedWebhookServiceServer) Deactivate(context.Context, *DeactivateRequest) (*DeactivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deactivate not implemented")
}
func (UnimplementedWebhookServiceServer) Activate(context.Context, *ActivateRequest) (*ActivateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Activate not implemented")
}
func (UnimplementedWebhookServiceServer) RotateSecret(context.Context, *RotateSecretRequest) (*RotateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateSecret not implemented")
}
func (UnimplementedWebhookServiceServer) mustEmbedUnimplementedWebhookServiceServer() {}
func (UnimplementedWebhookServiceServer) testEmbeddedByValue()                        {}

// UnsafeWebhookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookServiceServer will
// result in compilation errors.
type UnsafeWebhookServiceServer interface {
	mustEmbedUnimplementedWebhookServiceServer()
}

func RegisterWebhookServiceServer(s grpc.ServiceRegistrar, srv WebhookServiceServer) {
	// If the following call panics, it indicates UnimplementedWebhookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookService_ServiceDesc, srv)
}

func _WebhookService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebhookServiceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).Get(ctx, req.(*WebhookServiceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_Deactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).Deactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_Deactivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).Deactivate(ctx, req.(*DeactivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_Activate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).Activate(ctx, req.(*ActivateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_RotateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).RotateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_RotateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).RotateSecret(ctx, req.(*RotateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookService_ServiceDesc is the grpc.ServiceDesc for WebhookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.v1.WebhookService",
	HandlerType: (*WebhookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WebhookService_Register_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WebhookService_Get_Handler,
		},
		{
			MethodName: "Deactivate",
			Handler:    _WebhookService_Deactivate_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _WebhookService_Activate_Handler,
		},
		{
			MethodName: "RotateSecret",
			Handler:    _WebhookService_RotateSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/v1/webhook.proto",
}
