// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: notification/v1/webhook.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where to POST outcomes. https, and not an address inside our own network:
	// a callback makes US call somewhere THEY chose, so without that check a
	// source could reach anything we can.
	CallbackUrl   string `protobuf:"bytes,1,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_notification_v1_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

// Empty, and each rpc still gets its own. They would be one message today and
// four the first time any of them needs a field; sharing one now would make
// that day a breaking change for all four.
//
// Get's name is the service's own because both services here have a Get, and
// one proto package cannot hold two GetRequests.
type WebhookServiceGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookServiceGetRequest) Reset() {
	*x = WebhookServiceGetRequest{}
	mi := &file_notification_v1_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookServiceGetRequest) ProtoMessage() {}

func (x *WebhookServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookServiceGetRequest.ProtoReflect.Descriptor instead.
func (*WebhookServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{1}
}

type RotateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSecretRequest) Reset() {
	*x = RotateSecretRequest{}
	mi := &file_notification_v1_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSecretRequest) ProtoMessage() {}

func (x *RotateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSecretRequest.ProtoReflect.Descriptor instead.
func (*RotateSecretRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{2}
}

type RotateSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new secret, returned exactly once. Nothing hands it back afterwards.
	Secret        string `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateSecretResponse) Reset() {
	*x = RotateSecretResponse{}
	mi := &file_notification_v1_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateSecretResponse) ProtoMessage() {}

func (x *RotateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateSecretResponse.ProtoReflect.Descriptor instead.
func (*RotateSecretResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *RotateSecretResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type DeactivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateRequest) Reset() {
	*x = DeactivateRequest{}
	mi := &file_notification_v1_webhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateRequest) ProtoMessage() {}

func (x *DeactivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateRequest.ProtoReflect.Descriptor instead.
func (*DeactivateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{4}
}

type ActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_notification_v1_webhook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{5}
}

// The responses wrap the webhook rather than being it. An rpc that answers with
// a bare resource has nowhere to put a second field, and the first time one is
// needed every client breaks.
type RegisterResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Webhook *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// The signing secret, returned ONLY on the first registration and never
	// again -- what is stored is encrypted, and nothing reads it back except the
	// signing itself. Keep it; a source that loses it calls RotateSecret.
	//
	// Empty when this call changed the address of a callback that already
	// existed. The existing secret still stands, and rotating it silently would
	// break every receiver that was already verifying.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_notification_v1_webhook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *RegisterResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type WebhookServiceGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookServiceGetResponse) Reset() {
	*x = WebhookServiceGetResponse{}
	mi := &file_notification_v1_webhook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookServiceGetResponse) ProtoMessage() {}

func (x *WebhookServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookServiceGetResponse.ProtoReflect.Descriptor instead.
func (*WebhookServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{7}
}

func (x *WebhookServiceGetResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type DeactivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateResponse) Reset() {
	*x = DeactivateResponse{}
	mi := &file_notification_v1_webhook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateResponse) ProtoMessage() {}

func (x *DeactivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateResponse.ProtoReflect.Descriptor instead.
func (*DeactivateResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivateResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type ActivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateResponse) Reset() {
	*x = ActivateResponse{}
	mi := &file_notification_v1_webhook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateResponse) ProtoMessage() {}

func (x *ActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateResponse.ProtoReflect.Descriptor instead.
func (*ActivateResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{9}
}

func (x *ActivateResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

type Webhook struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CallbackUrl string                 `protobuf:"bytes,2,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	IsActive    bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// How many callbacks in a row have failed. Any success clears it; reaching
	// the configured limit switches the callback off, so a dead endpoint is not
	// called once per message forever.
	ConsecutiveFailures int32                  `protobuf:"varint,4,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_notification_v1_webhook_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_webhook_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_notification_v1_webhook_proto_rawDescGZIP(), []int{10}
}

func (x *Webhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webhook) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *Webhook) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Webhook) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *Webhook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Webhook) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_notification_v1_webhook_proto protoreflect.FileDescriptor

const file_notification_v1_webhook_proto_rawDesc = "" +
	"\n" +
	"\x1dnotification/v1/webhook.proto\x12\x0fnotification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fcallback_url\x18\x01 \x01(\tR\vcallbackUrl\"\x1a\n" +
	"\x18WebhookServiceGetRequest\"\x15\n" +
	"\x13RotateSecretRequest\".\n" +
	"\x14RotateSecretResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"\x13\n" +
	"\x11DeactivateRequest\"\x11\n" +
	"\x0fActivateRequest\"^\n" +
	"\x10RegisterResponse\x122\n" +
	"\awebhook\x18\x01 \x01(\v2\x18.notification.v1.WebhookR\awebhook\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"O\n" +
	"\x19WebhookServiceGetResponse\x122\n" +
	"\awebhook\x18\x01 \x01(\v2\x18.notification.v1.WebhookR\awebhook\"H\n" +
	"\x12DeactivateResponse\x122\n" +
	"\awebhook\x18\x01 \x01(\v2\x18.notification.v1.WebhookR\awebhook\"F\n" +
	"\x10ActivateResponse\x122\n" +
	"\awebhook\x18\x01 \x01(\v2\x18.notification.v1.WebhookR\awebhook\"\x82\x02\n" +
	"\aWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcallback_url\x18\x02 \x01(\tR\vcallbackUrl\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x121\n" +
	"\x14consecutive_failures\x18\x04 \x01(\x05R\x13consecutiveFailures\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xc4\x03\n" +
	"\x0eWebhookService\x12O\n" +
	"\bRegister\x12 .notification.v1.RegisterRequest\x1a!.notification.v1.RegisterResponse\x12\\\n" +
	"\x03Get\x12).notification.v1.WebhookServiceGetRequest\x1a*.notification.v1.WebhookServiceGetResponse\x12U\n" +
	"\n" +
	"Deactivate\x12\".notification.v1.DeactivateRequest\x1a#.notification.v1.DeactivateResponse\x12O\n" +
	"\bActivate\x12 .notification.v1.ActivateRequest\x1a!.notification.v1.ActivateResponse\x12[\n" +
	"\fRotateSecret\x12$.notification.v1.RotateSecretRequest\x1a%.notification.v1.RotateSecretResponseB\xc2\x01\n" +
	"\x13com.notification.v1B\fWebhookProtoP\x01Z@github.com/Serajian/srosha/sdk/go/notification/v1;notificationv1\xa2\x02\x03NXX\xaa\x02\x0fNotification.V1\xca\x02\x0fNotification\\V1\xe2\x02\x1bNotification\\V1\\GPBMetadata\xea\x02\x10Notification::V1b\x06proto3"

var (
	file_notification_v1_webhook_proto_rawDescOnce sync.Once
	file_notification_v1_webhook_proto_rawDescData []byte
)

func file_notification_v1_webhook_proto_rawDescGZIP() []byte {
	file_notification_v1_webhook_proto_rawDescOnce.Do(func() {
		file_notification_v1_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_webhook_proto_rawDesc), len(file_notification_v1_webhook_proto_rawDesc)))
	})
	return file_notification_v1_webhook_proto_rawDescData
}

var file_notification_v1_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_notification_v1_webhook_proto_goTypes = []any{
	(*RegisterRequest)(nil),           // 0: notification.v1.RegisterRequest
	(*WebhookServiceGetRequest)(nil),  // 1: notification.v1.WebhookServiceGetRequest
	(*RotateSecretRequest)(nil),       // 2: notification.v1.RotateSecretRequest
	(*RotateSecretResponse)(nil),      // 3: notification.v1.RotateSecretResponse
	(*DeactivateRequest)(nil),         // 4: notification.v1.DeactivateRequest
	(*ActivateRequest)(nil),           // 5: notification.v1.ActivateRequest
	(*RegisterResponse)(nil),          // 6: notification.v1.RegisterResponse
	(*WebhookServiceGetResponse)(nil), // 7: notification.v1.WebhookServiceGetResponse
	(*DeactivateResponse)(nil),        // 8: notification.v1.DeactivateResponse
	(*ActivateResponse)(nil),          // 9: notification.v1.ActivateResponse
	(*Webhook)(nil),                   // 10: notification.v1.Webhook
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_notification_v1_webhook_proto_depIdxs = []int32{
	10, // 0: notification.v1.RegisterResponse.webhook:type_name -> notification.v1.Webhook
	10, // 1: notification.v1.WebhookServiceGetResponse.webhook:type_name -> notification.v1.Webhook
	10, // 2: notification.v1.DeactivateResponse.webhook:type_name -> notification.v1.Webhook
	10, // 3: notification.v1.ActivateResponse.webhook:type_name -> notification.v1.Webhook
	11, // 4: notification.v1.Webhook.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: notification.v1.Webhook.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: notification.v1.WebhookService.Register:input_type -> notification.v1.RegisterRequest
	1,  // 7: notification.v1.WebhookService.Get:input_type -> notification.v1.WebhookServiceGetRequest
	4,  // 8: notification.v1.WebhookService.Deactivate:input_type -> notification.v1.DeactivateRequest
	5,  // 9: notification.v1.WebhookService.Activate:input_type -> notification.v1.ActivateRequest
	2,  // 10: notification.v1.WebhookService.RotateSecret:input_type -> notification.v1.RotateSecretRequest
	6,  // 11: notification.v1.WebhookService.Register:output_type -> notification.v1.RegisterResponse
	7,  // 12: notification.v1.WebhookService.Get:output_type -> notification.v1.WebhookServiceGetResponse
	8,  // 13: notification.v1.WebhookService.Deactivate:output_type -> notification.v1.DeactivateResponse
	9,  // 14: notification.v1.WebhookService.Activate:output_type -> notification.v1.ActivateResponse
	3,  // 15: notification.v1.WebhookService.RotateSecret:output_type -> notification.v1.RotateSecretResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_notification_v1_webhook_proto_init() }
func file_notification_v1_webhook_proto_init() {
	if File_notification_v1_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_webhook_proto_rawDesc), len(file_notification_v1_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_webhook_proto_goTypes,
		DependencyIndexes: file_notification_v1_webhook_proto_depIdxs,
		MessageInfos:      file_notification_v1_webhook_proto_msgTypes,
	}.Build()
	File_notification_v1_webhook_proto = out.File
	file_notification_v1_webhook_proto_goTypes = nil
	file_notification_v1_webhook_proto_depIdxs = nil
}
